# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-25 13:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20171025_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_dated',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 25, 13, 50, 30, 706886, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 25, 13, 50, 30, 706398, tzinfo=utc)),
        ),
    ]
