# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-26 10:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20171026_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_dated',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 26, 10, 30, 52, 297475, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 26, 10, 30, 52, 296963, tzinfo=utc)),
        ),
    ]
